### ISSUE TITLE
Add it to highlight.js

### ISSUE THREAD

**Issue by padreputativo** [highlightjs/highlightjs-gdscript#14]
I would love to use it in Discord and the only way to do it is being part of the main repo.

Please ask for the add to the main repo here:

https://highlightjs.readthedocs.io/en/latest/language-requests.html
https://github.com/highlightjs/highlight.js/issues/new/choose

Many thanks!

**Comment by joshgoebel** [comment]
This has been discussed many times in the past.  TLDR:

Highlight.js maintainers simply do not have time to support/maintain further grammars.

If Discord wished to use 3rd party grammars they **easily** can.  This is a Discord issue, not Highlight.js.

**Comment by padreputativo** [comment]
They accept to include external mantained languages.

**Comment by padreputativo** [comment]
If you wanna vote...

https://support.discord.com/hc/en-us/community/posts/12189095851927-Add-GDScript-to-the-code-highlighting
