### ISSUE TITLE
move gdscript.js to root directory.

### ISSUE THREAD

**Issue by fengjiongmax** [highlightjs/highlightjs-gdscript#8]
Hello, I'm trying to make [highlight.dart](https://github.com/git-touch/highlight.dart) support GDScript, which has the language definition files generated from highlight.js.
However, unlike [highlightjs-vue](https://github.com/highlightjs/highlightjs-vue) or [highlightjs-graphql](https://github.com/dpeek/highlightjs-graphql) have the language definition files in the root directory, gdscript.js located in `src/languages`.
And I think it's also confusing having [package.json](https://github.com/highlightjs/highlightjs-gdscript/blob/master/package.json#L5)'s `main` value set to `gdscript.js` where there's no such file in the root directory.

**Comment by joshgoebel** [comment]
The `main` key should be updated, `src/languages` is the correct location by convention.

**Comment by fengjiongmax** [comment]
Following @joshgoebel 's instruction, I've created a PR. 
And GDScript syntax definition file for highlight.dart can be generated from this repository, thanks.
